# Generated by Django 4.2.6 on 2023-11-09 11:30

import core.fields.identifier
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permission', '0000_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectPermission',
            fields=[
                ('object_pk', models.CharField(help_text='Used for linked key object', verbose_name='object id')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='object permission user id')),
                ('content_type', models.ForeignKey(help_text='Used for linked key content type', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(help_text='Used for linked key user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store user object permission',
                'db_table': '"permission"."object_permission_user"',
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_pk'], name='object_perm_content_bf8ea8_idx')],
                'unique_together': {('user', 'permission', 'object_pk')},
            },
        ),
        migrations.CreateModel(
            name='GroupObjectPermission',
            fields=[
                ('object_pk', models.CharField(help_text='Used for linked key object', verbose_name='object id')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='object permission group id')),
                ('content_type', models.ForeignKey(help_text='Used for linked key content type', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('group', models.ForeignKey(help_text='Used for linked key group', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Used store group object permission',
                'db_table': '"permission"."object_permission_group"',
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_pk'], name='object_perm_content_0f7004_idx')],
                'unique_together': {('group', 'permission', 'object_pk')},
            },
        ),
    ]
