# Generated by Django 5.0 on 2024-01-02 06:24

import core.fields.identifier
import core.models.base
import django.db.models.deletion
import django.utils.timezone
import library.modelutils.fields
import library.simplehistory.models
import report.fields.kwargs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0000_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('schema_id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='schema id')),
                ('schema_name', models.CharField(help_text='Used for view', unique=True, verbose_name='schema name')),
                ('database', models.CharField(default='default', help_text='Used for database alias', verbose_name='database')),
                ('query', models.TextField(help_text='Used for auto generate table view', null=True, verbose_name='query')),
            ],
            options={
                'verbose_name': 'Used store schema',
                'db_table': '"report"."schema"',
                'managed': True,
            },
            bases=(core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchema',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('schema_id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='schema id')),
                ('schema_name', models.CharField(db_index=True, help_text='Used for view', verbose_name='schema name')),
                ('database', models.CharField(default='default', help_text='Used for database alias', verbose_name='database')),
                ('query', models.TextField(help_text='Used for auto generate table view', null=True, verbose_name='query')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Used store history schema',
                'verbose_name_plural': 'historical Used store schemas',
                'db_table': '"history"."report_schema"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchemaField',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('schema_field_id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='schema field id')),
                ('schema_field_name', models.CharField(help_text='Used for view', verbose_name='schema field name')),
                ('class_name', models.CharField(help_text='Used for django field class', verbose_name='class name')),
                ('kwargs', report.fields.kwargs.FieldKwargsJSON(default=dict, help_text='Used for propertie field', verbose_name='kwargs')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='report.schema', verbose_name='schema')),
            ],
            options={
                'verbose_name': 'Used store history schema field',
                'verbose_name_plural': 'historical Used store schema fields',
                'db_table': '"history"."report_schema_field"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('schema_field_id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='schema field id')),
                ('schema_field_name', models.CharField(help_text='Used for view', verbose_name='schema field name')),
                ('class_name', models.CharField(help_text='Used for django field class', verbose_name='class name')),
                ('kwargs', report.fields.kwargs.FieldKwargsJSON(default=dict, help_text='Used for propertie field', verbose_name='kwargs')),
                ('schema', models.ForeignKey(help_text='Used for linked key', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='report.schema', verbose_name='schema')),
            ],
            options={
                'verbose_name': 'Used store schema field',
                'db_table': '"report"."schema_field"',
                'ordering': ('schema_field_id',),
                'managed': True,
                'unique_together': {('schema_field_name', 'schema')},
            },
            bases=(core.models.base.BaseStatus, models.Model),
        ),
    ]
