# Generated by Django 4.2.6 on 2023-11-09 11:30

import core.fields.identifier
import core.fields.status
import core.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import library.modelutils.fields
import library.simplehistory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0000_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('comment_id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='comment id')),
                ('object_id', models.CharField(help_text='Used for linked key commented object', verbose_name='object id')),
                ('message', models.TextField(verbose_name='message')),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('status', core.fields.status.StatusField(choices=[('draft', 'Draft'), ('published', 'Published'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='draft', max_length=100, no_check_for_status=True)),
                ('content_type', models.ForeignKey(help_text='Used for linked key model comment', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('parent', models.ForeignKey(blank=True, help_text='Used for hierarchy parent id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_set', to='comment.comment', verbose_name='parent')),
                ('user', models.ForeignKey(blank=True, help_text='Used for linked key author comment', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store comment',
                'db_table': '"comment"."comment"',
                'managed': True,
            },
            bases=(core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='CommentFlag',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.PositiveIntegerField(default=0, help_text='Used for count flag', verbose_name='count')),
                ('state', models.SmallIntegerField(choices=[(1, 'Unflagged'), (2, 'Flagged'), (3, 'Flag rejected by the moderator'), (4, 'Comment modified by the author')], default=1, help_text='Used for state flag', verbose_name='state')),
                ('comment', models.OneToOneField(help_text='Used for linked key comment', on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='comment.comment', verbose_name='comment')),
                ('moderator', models.ForeignKey(blank=True, help_text='Used for linked key moderator first flag', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
            ],
            options={
                'verbose_name': 'Used store comment flag',
                'db_table': '"comment"."comment_flag"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='id')),
                ('like', models.PositiveIntegerField(default=0, help_text='Used for count like', verbose_name='like')),
                ('dislike', models.PositiveIntegerField(default=0, help_text='Used for count dislike', verbose_name='dislike')),
                ('comment', models.OneToOneField(help_text='Used for linked key comment', on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='comment.comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Used store comment reaction',
                'db_table': '"comment"."comment_reaction"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommentReactionReason',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='id')),
                ('reaction_type', models.SmallIntegerField(choices=[(1, 'LIKE'), (2, 'DISLIKE')], help_text='Used for reaction type like or dislike', verbose_name='reaction type')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key reaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.commentreaction', verbose_name='reaction')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store history comment reaction reason',
                'verbose_name_plural': 'historical Used store comment reaction reasons',
                'db_table': '"history"."comment_reaction_reason"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommentReaction',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='id')),
                ('like', models.PositiveIntegerField(default=0, help_text='Used for count like', verbose_name='like')),
                ('dislike', models.PositiveIntegerField(default=0, help_text='Used for count dislike', verbose_name='dislike')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comment', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.comment', verbose_name='comment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Used store history comment reaction',
                'verbose_name_plural': 'historical Used store comment reactions',
                'db_table': '"history"."comment_comment_reaction"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommentFlagReason',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='id')),
                ('reason', models.TextField(blank=True, help_text='Used for reason flag', null=True, verbose_name='reason')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('flag', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key flag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.commentflag', verbose_name='flag')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key user flag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store history comment flag reason',
                'verbose_name_plural': 'historical Used store comment flag reasons',
                'db_table': '"history"."comment_flag_reason"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommentFlag',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='id')),
                ('count', models.PositiveIntegerField(default=0, help_text='Used for count flag', verbose_name='count')),
                ('state', models.SmallIntegerField(choices=[(1, 'Unflagged'), (2, 'Flagged'), (3, 'Flag rejected by the moderator'), (4, 'Comment modified by the author')], default=1, help_text='Used for state flag', verbose_name='state')),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comment', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.comment', verbose_name='comment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key moderator first flag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
            ],
            options={
                'verbose_name': 'Used store history comment flag',
                'verbose_name_plural': 'historical Used store comment flags',
                'db_table': '"history"."comment_comment_flag"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_removed', models.BooleanField(default=False)),
                ('comment_id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='comment id')),
                ('object_id', models.CharField(help_text='Used for linked key commented object', verbose_name='object id')),
                ('message', models.TextField(verbose_name='message')),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('status', core.fields.status.StatusField(choices=[('draft', 'Draft'), ('published', 'Published'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='draft', max_length=100, no_check_for_status=True)),
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key model comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='content type')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for hierarchy parent id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.comment', verbose_name='parent')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key author comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store history comment',
                'verbose_name_plural': 'historical Used store comments',
                'db_table': '"history"."comment_comment"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='CommentReactionReason',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='id')),
                ('reaction_type', models.SmallIntegerField(choices=[(1, 'LIKE'), (2, 'DISLIKE')], help_text='Used for reaction type like or dislike', verbose_name='reaction type')),
                ('reaction', models.ForeignKey(help_text='Used for linked key reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comment.commentreaction', verbose_name='reaction')),
                ('user', models.ForeignKey(help_text='Used for linked key user', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store comment reaction reason',
                'db_table': '"comment"."comment_reaction_reason"',
                'managed': True,
                'unique_together': {('user', 'reaction')},
            },
        ),
        migrations.CreateModel(
            name='CommentFlagReason',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='id')),
                ('reason', models.TextField(blank=True, help_text='Used for reason flag', null=True, verbose_name='reason')),
                ('flag', models.ForeignKey(help_text='Used for linked key flag', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='comment.commentflag', verbose_name='flag')),
                ('user', models.ForeignKey(help_text='Used for linked key user flag', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Used store comment flag reason',
                'db_table': '"comment"."comment_flag_reason"',
                'ordering': ('created',),
                'managed': True,
                'unique_together': {('flag', 'user')},
            },
        ),
    ]
